# Generated by Django 5.2.1 on 2026-05-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("writers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiteraryGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nomi"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Tavsifi")),
            ],
            options={
                "verbose_name": "Janr",
                "verbose_name_plural": "Janrlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LiteraryWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Oʻzgartirilgan vaqti"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavhasi")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="URL slug"
                    ),
                ),
                ("description", models.TextField(verbose_name="Qisqa tavsifi")),
                (
                    "introduction",
                    models.TextField(blank=True, verbose_name="Muqaddima/Kontekst"),
                ),
                ("content", models.TextField(verbose_name="Matn")),
                ("publication_year", models.IntegerField(verbose_name="Nashr yili")),
                (
                    "original_language",
                    models.CharField(
                        default="Uzbek", max_length=50, verbose_name="Asl tili"
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
                ),
                (
                    "downloads_count",
                    models.IntegerField(
                        default=0, verbose_name="Yuklab olinishlar soni"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Reytingi",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="works/covers/",
                        verbose_name="Muqova rasmi",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Asosiy asar"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Eʼlon qilingan"),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="works",
                        to="works.literarygenre",
                        verbose_name="Janri",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="writers.writer",
                        verbose_name="Muallifi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adabiy asar",
                "verbose_name_plural": "Adabiy asarlar",
                "ordering": ["-publication_year", "title"],
            },
        ),
        migrations.CreateModel(
            name="BookFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Oʻzgartirilgan vaqti"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("epub", "EPUB"),
                            ("txt", "Text"),
                            ("html", "HTML"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Fayl turi",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="works/files/", verbose_name="Fayl"),
                ),
                (
                    "pages_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sahifalar soni"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        help_text="Bytes da", verbose_name="Fayl hajmi"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="Uzbek", max_length=50, verbose_name="Tili"
                    ),
                ),
                (
                    "work",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_file",
                        to="works.literarywork",
                        verbose_name="Asar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kitob fayli",
                "verbose_name_plural": "Kitob fayllar",
            },
        ),
        migrations.AddIndex(
            model_name="literarywork",
            index=models.Index(
                fields=["writer", "publication_year"],
                name="works_liter_writer__c0244a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="literarywork",
            index=models.Index(fields=["slug"], name="works_liter_slug_9693dc_idx"),
        ),
        migrations.AddIndex(
            model_name="literarywork",
            index=models.Index(
                fields=["is_published"], name="works_liter_is_publ_aa46e8_idx"
            ),
        ),
    ]
