services:
  - type: web
    name: adiblar-merosi-backend
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application --access-logfile - --error-logfile - --capture-output --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.13
