# Generated by Django 5.2.1 on 2026-05-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Writer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Oʻzgartirilgan vaqti"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ismi")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Familiyasi"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="writers/images/",
                        verbose_name="Rasmi",
                    ),
                ),
                (
                    "short_bio",
                    models.TextField(
                        max_length=500, verbose_name="Qisqa maʼlumot (Overview)"
                    ),
                ),
                ("detailed_bio", models.TextField(verbose_name="Batafsil biografiya")),
                ("birth_date", models.DateField(verbose_name="Tug'ilgan sanasi")),
                (
                    "death_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vafot etgan sanasi"
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(max_length=255, verbose_name="Tug'ilgan joyı"),
                ),
                (
                    "death_place",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Vafot etgan joyı",
                    ),
                ),
                (
                    "creative_period_start",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ijod davri boshi (yil)"
                    ),
                ),
                (
                    "creative_period_end",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ijod davri oxiri (yil)"
                    ),
                ),
                (
                    "main_genres",
                    models.CharField(
                        help_text="Vergul bilan ajratilgan",
                        max_length=255,
                        verbose_name="Asosiy janrlar",
                    ),
                ),
                (
                    "influenced_by",
                    models.CharField(
                        blank=True,
                        help_text="Vergul bilan ajratilgan",
                        max_length=255,
                        verbose_name="Taʼsiri qilgan mutafakkirlar",
                    ),
                ),
                (
                    "influenced",
                    models.CharField(
                        blank=True,
                        help_text="Vergul bilan ajratilgan",
                        max_length=255,
                        verbose_name="Taʼsir qilgan shoxislar",
                    ),
                ),
                (
                    "legacy",
                    models.TextField(blank=True, verbose_name="Merosi va taʼsiri"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Yozuvchi",
                "verbose_name_plural": "Yozuvchilar",
                "ordering": ["birth_date"],
                "indexes": [
                    models.Index(fields=["slug"], name="writers_wri_slug_7ecfd9_idx"),
                    models.Index(
                        fields=["is_active"], name="writers_wri_is_acti_f2f796_idx"
                    ),
                ],
            },
        ),
    ]
