# Generated by Django 5.2.1 on 2026-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Familiyasi'),
        ),
    ]
