# Generated by Django 5.2.1 on 2026-05-11 12:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oʻzgartirilgan vaqti')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('topic', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=25, verbose_name='Davomiyligi (daq)')),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Murakkab')], default='intermediate', max_length=20, verbose_name='Daraja')),
                ('pass_percent', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="O'tish foizi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['slug'], name='common_prac_slug_a477ba_idx'), models.Index(fields=['is_active'], name='common_prac_is_acti_2946af_idx')],
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oʻzgartirilgan vaqti')),
                ('prompt', models.TextField(verbose_name='Savol matni')),
                ('explanation', models.TextField(blank=True, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='common.practicetest', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test savoli',
                'verbose_name_plural': 'Test savollari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oʻzgartirilgan vaqti')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oylik miqdori')),
                ('requirements', models.TextField(help_text='Har bir talabni yangi qatordan yozing', verbose_name='Talablar')),
                ('deadline', models.DateField(verbose_name='Ariza muddati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_open', models.BooleanField(default=True, verbose_name='Qabul ochiq')),
            ],
            options={
                'verbose_name': 'Stipendiya dasturi',
                'verbose_name_plural': 'Stipendiya dasturlari',
                'ordering': ['deadline', 'name'],
                'indexes': [models.Index(fields=['slug'], name='common_scho_slug_d39c85_idx'), models.Index(fields=['is_active', 'is_open'], name='common_scho_is_acti_58c15b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oʻzgartirilgan vaqti')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('university', models.CharField(max_length=255, verbose_name='Universitet')),
                ('study_year', models.CharField(blank=True, max_length=50, verbose_name='Kurs')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='GPA')),
                ('motivation_letter', models.TextField(verbose_name='Motivatsion xat')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio havolasi')),
                ('status', models.CharField(choices=[('submitted', 'Yuborilgan'), ('reviewing', "Ko'rib chiqilmoqda"), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan')], default='submitted', max_length=12, verbose_name='Holat')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaror vaqti')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL, verbose_name='Arizachi')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='common.scholarshipprogram', verbose_name='Dastur')),
            ],
            options={
                'verbose_name': 'Stipendiya arizasi',
                'verbose_name_plural': 'Stipendiya arizalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oʻzgartirilgan vaqti')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savol')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('score_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Foiz natijasi')),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sarflangan vaqt (sek)')),
                ('answers_data', models.JSONField(blank=True, default=dict, verbose_name='Javoblar')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='common.practicetest', verbose_name='Test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oʻzgartirilgan vaqti')),
                ('option_text', models.CharField(max_length=500, verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='common.practicequestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Savol varianti',
                'verbose_name_plural': 'Savol variantlari',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['question', 'order'], name='common_prac_questio_12721a_idx')],
                'unique_together': {('question', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='practicequestion',
            index=models.Index(fields=['test', 'order'], name='common_prac_test_id_5362ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='practicequestion',
            unique_together={('test', 'order')},
        ),
        migrations.AddIndex(
            model_name='scholarshipapplication',
            index=models.Index(fields=['status'], name='common_scho_status_35290a_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipapplication',
            index=models.Index(fields=['program', 'status'], name='common_scho_program_51e792_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scholarshipapplication',
            unique_together={('program', 'applicant')},
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test'], name='common_test_test_id_c40e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user'], name='common_test_user_id_6e0de0_idx'),
        ),
    ]
