# Generated by Django 5.2.1 on 2026-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AddField(
            model_name='practicetest',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AddIndex(
            model_name='practicetest',
            index=models.Index(fields=['starts_at'], name='common_prac_starts__b39813_idx'),
        ),
        migrations.AddIndex(
            model_name='practicetest',
            index=models.Index(fields=['expires_at'], name='common_prac_expires_762f15_idx'),
        ),
    ]
