# Generated by Django 5.2.1 on 2026-05-11 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("works", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Oʻzgartirilgan vaqti"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/avatars/",
                        verbose_name="Avatari",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Biografiya"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefon raqami"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Veb-sayt")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Manzili"
                    ),
                ),
                (
                    "article_count",
                    models.IntegerField(default=0, verbose_name="Maqolalar soni"),
                ),
                (
                    "joined_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ruyxatlanish sanasi"
                    ),
                ),
                (
                    "receive_email_notifications",
                    models.BooleanField(default=True, verbose_name="Email xabarlari"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi profili",
                "verbose_name_plural": "Foydalanuvchi profillari",
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Oʻzgartirilgan vaqti"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_by",
                        to="works.literarywork",
                        verbose_name="Asar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saqlangan asar",
                "verbose_name_plural": "Saqlangan asarlar",
                "ordering": ["-created_at"],
                "unique_together": {("user", "work")},
            },
        ),
    ]
