# Generated by Django 5.2.1 on 2026-05-11 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("writers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nomi"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Teg",
                "verbose_name_plural": "Teglar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Oʻzgartirilgan vaqti"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavhasi")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "summary",
                    models.TextField(max_length=500, verbose_name="Qisqa tavsifi"),
                ),
                ("content", models.TextField(verbose_name="Matn")),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="articles/images/",
                        verbose_name="Asosiy rasmi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralamaʼ"),
                            ("pending", "Kutilmoqda"),
                            ("published", "Eʼlon qilingan"),
                            ("rejected", "Rad etilgan"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Admin izohoti"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yuborilgan vaqti"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Eʼlon qilingan vaqti"
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Muallifi",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles_about",
                        to="writers.writer",
                        verbose_name="Haqida yozuvchi",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="articles.tag",
                        verbose_name="Teglar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maqola",
                "verbose_name_plural": "Maqolalar",
                "ordering": ["-published_at", "-submitted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Oʻzgartirilgan vaqti"
                    ),
                ),
                ("content", models.TextField(verbose_name="Matn")),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Tasdiqlangan"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="articles.article",
                        verbose_name="Maqola",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Muallifi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sharh",
                "verbose_name_plural": "Sharhlar",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["article", "is_approved"],
                        name="articles_ar_article_c9ff28_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "-published_at"], name="articles_ar_status_de59cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["writer", "status"], name="articles_ar_writer__af0406_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="articles_ar_slug_452037_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["author", "status"], name="articles_ar_author__8254d9_idx"
            ),
        ),
    ]
