# Generated by Django 5.2.1 on 2026-05-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/files/', verbose_name='Maqola fayli'),
        ),
    ]
